[package]
name = "GoogleDownload"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
indicatif = "0.17.8"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
tokio = { version = "1.40.0", features = ["full"] }
